# Database connection
db.host=localhost
db.port=3306
db.name=employee_management

spring.datasource.url=jdbc:mysql://${db.host}:${db.port}/${db.name}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}