# Application
spring.application.name=employee-management

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=8081

# Encoding cho log
logging.charset.console=UTF-8
logging.charset.file=UTF-8

# Logging configuration
logging.level.root=INFO
logging.level.com.example.employee_management=DEBUG

# Choose the environment of running
spring.profiles.active=dev

# Actuator configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Cache configuration
spring.cache.type=caffeine
spring.cache.cache-names=employeeCount
spring.cache.caffeine.spec=expireAfterWrite=60s
